version: '3'
services:
    cypress_test:
              image: cypress_compose
              build:
                    context: .
                    dockerfile: ./Dockerfile
              volumes:
                - ./dockerData/:/app/parsedData